### ISSUE TITLE
Is the project dead ?

### ISSUE THREAD

**Issue by Aeris1One** [Skaldebane/android-spotdl#1]
All's in the name !
What about this project, looks promising ! 
I'm at the moment using Termux to sync my "Liked" playlist with my phone, would be great to have a much smaller app dedicated to that !

**Comment by Skaldebane** [comment]
Hi there!
Yes, the project is still a thing, though as a high school student I barely work on anything now...

I've been having exactly the same hassle that you have with Termux, so I though it would be amazing to make an app that does that in a more user-friendly and more advanced way.

This project is not only to replicate spotdl's features into an app, but also to address some of the problems I encountered with spotdl. Hence this is a full rewrite of the whole functionality instead of being just an interface on top of spotdl... However, I might consider using spotdl first here.

However, I ain't got any exact dates for when will I work on it and when will it be done. Just press the "Watch" button to stay tuned.

(And hey, it's pretty cool to see that this project gained attraction... this excites me a lot!)

**Comment by Skaldebane** [comment]
Hi again! No more development will be done on this app. I guess there are already a few alternatives out there today, but in general I lost all code for this project, and just moved on to work on different project.

Anyways, thanks a lot for your interest!
